---
- name: Install required packages
  ansible.builtin.package:
    name: "{{ authselect_packages }}"
    state: present

- name: Manage user-nsswitch.conf
  ansible.builtin.template:
    src: "user-nsswitch.conf.j2"
    dest: "/etc/authselect/user-nsswitch.conf"
    mode: 0644
    owner: root
    group: root
  notify:
    - Update PAM with authselect

- name: Get current authselect config
  ansible.builtin.command: authselect current -r
  register: authselect_current_raw
  check_mode: false
  changed_when: false
  failed_when:
    - authselect_current_raw.rc != 0
    - '"No existing configuration detected" not in authselect_current_raw.stdout'

- name: Set fact authselect_force true if no existing configuration detected.
  ansible.builtin.set_fact:
    authselect_force: true
  when:
    - '"No existing configuration detected" in authselect_current_raw.stdout'

- name: Verify current authselect profile and features are in the desired state
  ansible.builtin.set_fact:
    authselect_current_profile: "{{ authselect_current_raw.stdout.split()[0] }}"
    authselect_current_features: "{{ authselect_current_raw.stdout.split()[1:] }}"
  changed_when:
    - authselect_profile != authselect_current_profile or authselect_features|sort != authselect_current_features|sort or
      authselect_current_raw.failed
  notify:
    - Update PAM with authselect
