---
- name: Update PAM with authselect
  ansible.builtin.command:
    argv: "{{ _argv }}"
  vars:
    _base_argv:
      - authselect
      - select
    _force:
      true:
        - '--force'
      false: []
    _argv: >-
      {{ _base_argv +  [authselect_profile] + authselect_features + _force[authselect_force] }}
