---
- name: Update PAM with authselect
  command:
    argv: "{{ _argv }}"
  vars:
    _base_argv:
      - authselect
      - select
    _argv: >
      {{ _base_argv
      +  [authselect_profile] + authselect_features
      + ['--force'] if authselect_force else [] }}
